### PR TITLE
Security: sandbox iframes, add rel="noopener nofollow" to absolute anchors

### PR DESCRIPTION
**Pull request by glebm**
This is a pre-emptive measure: there is not an actual vulnerability that I am aware of.

1. Add a sandbox to all `<iframe>`s. The sandbox is very permissive, but still better than no sandbox.
2. Add `rel="noopener nofollow"`, the former is to prevent a certain kind of phishing attacks, and the latter discourage spammers.

Also, removed the excessive `merge` calls. `Sanitize::Config.merge` is a deep merge already.

### CODE REVIEW

**Comment by glebm** [comment]
@ZogStriP Demo at https://plforums.org/misc/formatting-demo

**Comment by ZogStriP** [comment]
Sorry for the delay here, can you get the demo working again?

**Comment by glebm** [comment]
@ZogStriP I've updated the demo URL

**Comment by ZogStriP** [comment]
Thanks, looks good 👍

**Pull request merged**
