### PR TITLE
support for xkcd

### PR DESCRIPTION
**Pull request by thiagoarrais**
This PR adds support for oneboxing xkcd content

### CODE REVIEW

**Comment by thiagoarrais** [comment]
Tests are passing locally now. Let's see if Travis agrees...

I'm keeping this as WIP 'cause I still want to ditch the scraping approach and use the xkcd JSON API.

**Comment by thiagoarrais** [comment]
51899ea: just because I perceive the API to be more stable.

**Comment by thiagoarrais** [comment]
I think I'm done here. Let me know if you want the commits squashed or something.

**Comment by ZogStriP** [comment]
Looks good 😍  If you could squash the commits, that'd be awesome

**Comment by thiagoarrais** [comment]
@ZogStriP: done!

**Comment by thiagoarrais** [comment]
I also added a spec when squashing. Hope that isn't a problem.

**Pull request merged**
