### PR TITLE
Add trello onebox

### PR DESCRIPTION
**Pull request by davidtaylorhq**
This adds support for oneboxing trello 'boards' and 'cards'. Simply adapts the url into the correct format for an iframe embed.

https://meta.discourse.org/t/trello-card-onebox/24762/11?u=david_taylor

### CODE REVIEW

**Comment by eviltrout** [comment]
It looks good but it needs a test since it's a new onebox engine.

**Comment by davidtaylorhq** [comment]
Thanks @eviltrout, I've added a test. 

There's not a lot to test as it doesn't actually make any network requests to form the onebox. Let me know if there's anything else I can add to it.

**Comment by eviltrout** [comment]
Thanks cool, but it's still worth making sure the translation works in this case. Thanks for your work!

**Comment by davidtaylorhq** [comment]
@eviltrout does some magic need to happen for this change to appear on live discourse sites? It doesn't seem to be working on my freshly upgraded instance, and it's not working on meta either.

**Comment by eviltrout** [comment]
Not magic, but two steps are required:

- We have to bump the version of the gem and push it to rubygems
- We have to update Discourse to use that new version.

I'll do it shortly.

**Pull request merged**
