### PR TITLE
Fix linting issues and make the build pass

### PR DESCRIPTION
**Pull request by robbyoconnor**
Build was failing for at least the first fix. 

- AllCops/Excludes &AllCops/Includes is now AllCops/Exclude and AllCops/Includes
- Correct linting issues

### CODE REVIEW

**Comment by SamSaffron** [comment]
actually I prefer us to support 2.2 and up, as 2.2 is still a supported version of Ruby. 

@techAPJ  can you make sure we are not using &. in onebox?

**Comment by robbyoconnor** [comment]
@SamSaffron Still fixed some linting issues and also tweaked the travis config to run on the container infra

**Comment by techAPJ** [comment]
Thanks @robbyoconnor ❤️ 

@SamSaffron taking care of `&.` now.

**Comment by robbyoconnor** [comment]
@techAPJ I just fixed it

**Comment by techAPJ** [comment]
Version bumped with your fixes. :)

**Comment by robbyoconnor** [comment]
Great!

**Pull request merged**
