### PR TITLE
Update amazon.mustache to close strong element and generic template link to launch in separate window

### PR DESCRIPTION
**Pull request by rcanand**
strong element is not being closed at the end

### CODE REVIEW

**Comment by tgxworld** [comment]
I merged https://github.com/discourse/onebox/commit/fbf633b9cfbca4e0cf61fc42c3cc1f183da27c6c into master. Not sure about opening links in a separate page by default.  

cc @techAPJ

**Comment by techAPJ** [comment]
Hi @rcanand,

We do not support explicitly adding `target='_blank'` to links because it is controlled by Discourse user preference _Open all external links in a new tab_.

Thanks for the HTML fix! 👍

**Comment by techAPJ** [comment]
I discussed this with @tgxworld and @coding-horror and we agree that we can support explicitly adding `target='_blank'` to links inside the onebox.

Apologies for the confusion @rcanand and thanks for your work on this.

**Comment by tgxworld** [comment]
:+1:

**Comment by rcanand** [comment]
👍

**Pull request merged**
