### PR TITLE
[READY] fix bug in twitter onebox

### PR DESCRIPTION
**Pull request by tarzan**
the onebox couldn't be cached because of wrongly parsed timestamps
this fixes the error: `no _dump_data is defined for class Nokogiri::XML::Attr`

this is the alt. to #323

### CODE REVIEW

**Comment by tarzan** [comment]
@tgxworld I also squashed the commits. Is this ok?

**Comment by tgxworld** [comment]
Thanks for splitting up the PR @tarzan. What are the steps to reproduce this? From the code, I don't quite understand what it is fixing

**Comment by tarzan** [comment]
Previously, the timestamp extracted was a `Nokogiri::XML::Attr`-object which can not be cached because it can't be serialized. I changed it so it will be parsed as a string instead. I ran into this because we use redis for caching.

If you check out the branch and reverse the changes to the twitter engine, you'll see a failing spec showcasing the issue.

**Comment by tarzan** [comment]
you'll get:
```bash
Onebox::Engine::TwitterStatusOnebox
  with html
    behaves like an engine
      responds to data
      responds to record
      correctly matches the url
      #data
        includes title
        includes link
    behaves like #to_html
      includes tweet
      gets the correct timestamp (FAILED - 1)

Failures:

  1) Onebox::Engine::TwitterStatusOnebox with html behaves like #to_html gets the correct timestamp
     Failure/Error: expect(onebox.send(:timestamp)).to eq("6:59 PM - 1 Aug 2013")

       expected: "6:59 PM - 1 Aug 2013"
            got: #<Nokogiri::XML::Attr:0x3fd5a6493ad4 name="title" value="6:59 PM - 1 Aug 2013">

       (compared using ==)
```

**Comment by tarzan** [comment]
any news on this?

**Comment by SamSaffron** [comment]
@techAPJ can you review this as well

**Comment by techAPJ** [comment]
The changes looks good. Initiating Travis check again.

**Comment by techAPJ** [comment]
LGTM 👍 

Thank You @tarzan.

**Pull request merged**
