### PR TITLE
better no double negatives

### PR DESCRIPTION
**Pull request by y0va**
This fixes an issue with wrongly chosen og tags for generic sites

### CODE REVIEW

**Comment by eviltrout** [comment]
This is going to need a test. Could you add one please?

**Comment by ZogStriP** [comment]
Not sure I understand this change. Why change `if` into `unless` and not change the `&&` and `||` operators?

**Comment by y0va** [comment]
> Not sure I understand this change. Why change the if into unless and not change the && and || operators?

This is no change. It's a bugfix.

The og tags had not been read correctly. I've tested it against this: http://solidbase.dokku.ecobytes.net/test/test/

where actually this metadata should appear: 

```md
---
title: "This is og:title"
description: "this is og:description"
date: 2020-01-23
---

This is content
```

**Comment by SamSaffron** [comment]
I was thinking that, but Robin’s point stands, this is clearly a case that
is missing a test

**Comment by y0va** [comment]
Sorry, I'm very new to onebox. How do you test?

**Comment by eviltrout** [comment]
@y0va the tests are in the `spec` folder and you can run them with `bundle exec rspec`. I suggest you look at the other tests and see how to add a similar test for your new fix.

**Comment by CvX** [comment]
Onebox works correctly. The page you've tested it on has a `link rel="canonical"`:

```html
<link rel="canonical" href="http://solidbase.dokku.ecobytes.net/">
```

Onebox follows that link and returns `og:` metadata of that page.

**Pull request closed without merging**
