### PR TITLE
Added support for kaltura.com embed videos.

### PR DESCRIPTION
**Pull request by jessp01**

### CODE REVIEW

**Comment by zoharbabin** [comment]
@jzeta / @vykster - Is there a policy around merging pulls to this repo? Would love to have this merged for others to use.

Thanks!

**Comment by SamSaffron** [comment]
sorry for the MEGA delay here. 

This is complicated @zoharbabin / @jessp01  ... in general we are quite fast to merge but this particular one contains potential security concerns. In particular html_v2  worries me a bit as its injecting a player out of an iframe. 

I wonder if a better fit here is an additional plugin, or perhaps clean up this PR only to have the iframe version?

**Comment by SamSaffron** [comment]
Reading through: 

https://knowledge.kaltura.com/embedding-kaltura-media-players-your-site

Looks like there is a far simpler mechanism these days for the IFRAME embed - that does not append any javascript and so on, can we shift to use that?

**Comment by romanrizzi** [comment]
Hi everyone!

Just opened a PR to support this site building an iframe and a placeholder image directly from Open Graph.

Feedback from Kaltura.com users would be awesome!

**Comment by romanrizzi** [comment]
Since support was added in #395 I think we could close this PR

**Pull request closed without merging**
