### PR TITLE
Remove Status tags/indications on GH issues Onebox

### PR DESCRIPTION
**Pull request by Moter8**
Fixes https://meta.discourse.org/t/23790

### CODE REVIEW

**Comment by ZogStriP** [comment]
open/closed/merged (or anything that is transiant) should be removed since we don't have any way of updating the onebox.

**Comment by Moter8** [comment]
Why did you immediately close this? I could have changed it again.

**Comment by ZogStriP** [comment]
Sorry, I didn't want someone else to accidentaly merge that PR.

**Comment by Moter8** [comment]
There, I removed the status things from the template and the ruby file itself.

**Comment by ZogStriP** [comment]
Thanks, can you squash the commits into 1?

**Comment by Moter8** [comment]
Sorry, I tried to follow [this how-to](http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit) but that didn't seem to work :(

**Comment by ZogStriP** [comment]
You can open another PR ;) That's often easier :)

**Pull request closed without merging**
