### PR TITLE
Add ptt onebox

### PR DESCRIPTION
**Pull request by billy3321**
I added ptt parser for onebox.

The PTT Gossiping board need cookie support and post yes to ask18 page, so I use mechanize gem to do it.

### CODE REVIEW

**Comment by audreyt** [comment]
For context, [PTT](https://en.wikipedia.org/wiki/PTT_Bulletin_Board_System) is the Taiwan equivalent of Reddit; this feature was developed as part of the vTaiwan.tw deliberative rulemaking effort.

**Comment by SamSaffron** [comment]
@audreyt / @billy3321 totally open to bringing this in now, sorry we sat on it for so long. 

Sadly, it needs a bit of a rewrite though to strip out the mechanize dependency, since we no longer carry it around. Would you be open to that?

**Comment by audreyt** [comment]
Sure thing. It seems that `mechanize` is only used on two simple GET/POST requests anyway. Which module would you prefer that we switch to?

**Comment by SamSaffron** [comment]
Hi @audreyt I would recommend using the built in abstraction (its new) 

`Onebox::Helpers.fetch_response(url)`

**Comment by techAPJ** [comment]
Hi @audreyt,

Any update here? Feel free to ping me if you need any help here.

**Comment by techAPJ** [comment]
Closing this PR for now.

@billy3321 feel free to open another PR for it.

**Pull request closed without merging**
