### PR TITLE
[BUGFIX] fix pubmed onebox

### PR DESCRIPTION
**Pull request by tarzan**
only parse actual refs to articles and add support for electronic ones

### CODE REVIEW

**Comment by tarzan** [comment]
@tgxworld is it ok like this?

**Comment by tarzan** [comment]
any news on this?

**Comment by SamSaffron** [comment]
@techAPJ  can you review this and merge?

**Comment by techAPJ** [comment]
Looks good. Let's re-run specs.

**Comment by techAPJ** [comment]
Thanks for this PR @tarzan 👍

**Pull request merged**
