### PR TITLE
Feature: Twitter quote-tweets

### PR DESCRIPTION
**Pull request by jcalvento**
# Quoted tweets
## Depends on:
https://github.com/discourse/discourse/pull/7832

## Discussion:
https://meta.discourse.org/t/twitter-quote-tweets-not-shown-in-oneboxes/115963
### Preview:
N1ag4wJ

## Additional:
- Refactor code to remove duplication
- Add memoization to avoid loading several times the same variables and content
- Add more tests coverage to existing scenarios

### CODE REVIEW

**Comment by SamSaffron** [comment]
This looks like a nice improvement. @techAPJ  can you review?

**Comment by techAPJ** [comment]
PR looks great @jcalvento! 👍 

I see rubocop failure in Travis, make sure you run rubocop on edited files for proper formatting.

**Comment by jcalvento** [comment]
@techAPJ sure! I'll fix that and let you know. Thanks

**Comment by jcalvento** [comment]
@techAPJ @SamSaffron done. Ruby 2.3 build is failing during setup thought.
Btw, couldn't amend in master branch, if you want me to remove the last commit I can close this PR and create another branch to fix commits

**Comment by techAPJ** [comment]
Looks good, thanks @jcalvento 👍

**Pull request merged**
