### PR TITLE
Solves syntax error

### PR DESCRIPTION
**Pull request by yatindrarao**

### CODE REVIEW

**Comment by ZogStriP** [comment]
It's not a syntax error, it's a valid syntax as of Ruby 2.3 😉

**Comment by yatindrarao** [comment]
Sorry for that.

Can you please tell me what is version of **onebox gem** which supports **ruby 2.2** ?

**Comment by ZogStriP** [comment]
Not sure. You'll have to `git-bisect` it I guess... :|

**Comment by SamSaffron** [comment]
We probably should be somewhat less aggressive with Ruby support on onebox,
Ruby 2.1 and up is fine (2.0 is no longer supported)

**Pull request closed without merging**
