### PR TITLE
Add Repl.it onebox

### PR DESCRIPTION
**Pull request by amasad**
This is modeled after the [Audioboom onebox](https://github.com/discourse/onebox/blob/f36ae0690ea5cd06071a0f98c57df7bb42f4c793/lib/onebox/engine/audioboom_onebox.rb).

Here is what it looks like: 
screen shot 2016-12-27 at 5 15 46 pm

Reference discussion: https://meta.discourse.org/t/runnable-repl-it-embed/54522

### CODE REVIEW

**Comment by SamSaffron** [comment]
awesome, can you confirm there is no vector for abuse here? 

For example is there anyway someone can craft a link that will force users browsers to go to 100% ?

**Comment by amasad** [comment]
>awesome, can you confirm there is no vector for abuse here?

We take a lot of precautions here (e.g. languages that we run on the client-side, we server an iframe from replit.org so that it is restricted under the cross-origin resource policy) and never had a problem with this.

If it helps, our embed has been [vetted by Microsoft](https://blogs.office.com/2016/09/07/now-teachers-can-include-live-code-demo-in-onenote/).

**Comment by SamSaffron** [comment]
I see,

What if someone adds an embed to

while(true) {
   console.log("a");
}

In JavaScript.

This totally kills my browser tab in Chrome (can not even exit it)

If this is shared when does it execute? Are users going to have to click
"run" to make anything happen?

**Comment by amasad** [comment]
Yes, we don't auto-run -- they have to click "run".
(We used to sandbox JS in WebWorkers but people expected `alert` and `prompt` to work -- we're now looking at transforming the code to insert counters to detect and break long running loops)

**Comment by SamSaffron** [comment]
cool thanks for that, will let another member on the team review and get
this merged in :)

**Comment by ZogStriP** [comment]
LGTM 👍

**Comment by amasad** [comment]
Thanks!!

**Pull request merged**
