### PR TITLE
make tests pass on 2.2

### PR DESCRIPTION
**Pull request by robbyoconnor**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@techAPJ fixed the safe navigation operator usage.

**Comment by robbyoconnor** [comment]
:white_check_mark:  -- It's all green! :tada:

**Comment by techAPJ** [comment]
Awesome, thanks! 💚  💚

**Comment by robbyoconnor** [comment]
No problem -- I saw the failing tests and figured I'd fix it. 

Also no idea why rspec tests weren't being run on Travis but that's fixed too!

**Pull request merged**
